spring:
  jpa:
    hibernate:
      ddl-auto: validate

---
spring:
  config:
    activate:
      on-profile: localDev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mydb
    username: root
    password: rootPassword
    name: mydb
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
#      hibernate.format_sql: true
#    show-sql: true
    hibernate.ddl-auto: validate
  sql:
    init:
      platform: mysql
server:
  port: 8080
  tomcat:
    connection-timeout: -1
#  ssl:
#    key-store-type: PKCS12
#    key-store: src/main/resources/ships.p12
#    key-store-password: boomboom
#    key-alias: ships
#  error.whitelabel.enabled: false

management:
  endpoints:
    web:
      base-path: /manage
      exposure.include: "*"
  endpoint.health.show-details: always
logging:
  level:
    pl:
      ee:
        gameServer: TRACE
---
spring:
  config:
    activate:
      on-profile: productionDev
  datasource:
      url: mysql://34.74.51.210:3306/mydb

---
spring:
  config:
    activate:
      on-profile: production
  datasource:
#    user
#    username: gameServerUser
#    password: P4r4g0nF1skalny
#    root
    username: root
    password: 9v5i0kxlEEz4uxCL
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.52.160.2:3306/gameServer
    name: gameServer

  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate.ddl-auto: validate
  sql:
    init:
      continue-on-error: true
      enabled: true
logging:
  level: debug
  file:
    name: ships.log