spring:
  jpa:
    hibernate:
      ddl-auto: validate


  jackson:
    mapper:
      default-view-inclusion: true
logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: TRACE
server:
  port: 8080
  tomcat:
    connection-timeout: 60000
---
spring:
  config:
    activate:
      on-profile: localDev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/gameServer
    username: root
    password: rootPassword
    name: gameServer
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate.ddl-auto: create-drop
  sql:
    init:
      platform: mysql
management:
  endpoints:
    web:
      base-path: /manage
      exposure.include: "*"
  endpoint.health.show-details: always
logging:
  level:
    pl:
      ee:
        gameServer: TRACE
  file:
    name: ships.log
---
spring:
  config:
    activate:
      on-profile: productionDev
  datasource:
      url: mysql://34.74.51.210:3306/mydb

---
spring:
  config:
    activate:
      on-profile: production
  datasource:
    username: root
    password: 9v5i0kxlEEz4uxCL
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.52.160.2:3306/gameServer
    name: gameServer

  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      continue-on-error: true
      enabled: true
logging:
  level:
    pl:
      ee:
        gameServer: TRACE
  file:
    name: ships.log